### ISSUE TITLE
Considerar trabajar con rama "devel" hasta tener código definitivo

### ISSUE THREAD

**Issue by ghost** [DavidCharif/Grupo5#1]
Como el proyecto no es lo suficientemente grande, ni hay tanto tiempo, se puede considerar que todos los cambios los guardemos en una rama llamada devel, en la que podamos hacer y deshacer hasta tener un resultado que sea conforme. Además nos sirve de práctica.

**Comment by DavidCharif** [comment]
Concuerdo 👌
